# This file was generated by GoReleaser. DO NOT EDIT.
cask "anexia" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f2790c6e5c39b966a158a78f5d2c29489d9fcab7dceefd0c637a69fdbe331717"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
    on_arm do
      sha256 "b895f40cd8897137b57e510db8a484f6b2c63f87bb7dbb2eb6145e234dd7867f"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "21d172021d31400e579b4db7632620b2801b2b0d94800bada0d30e778bfff11d"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
    on_arm do
      sha256 "e297ef4c6bbd0ffc5383792667894f671b076cec5f053fba33ce43352dbf4884"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
  end

  name "anexia"
  desc "Command-line interface for the Anexia Engine API"
  homepage "https://github.com/ProbstenHias/anexia-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anexia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anexia"]
    end
  end

  # No zap stanza required

end
