# This file was generated by GoReleaser. DO NOT EDIT.
cask "anexia" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5de59c29ad4a9332110ec0678a265e6773f0ff341433df0fdf9dd35824d98052"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
    on_arm do
      sha256 "34ab43f22027ed1e2ce815842c7ceddd7c7e7273521004c27a70754c1587590a"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1258ea00c7a9d4916fd910645ddb84af780d40d69463be25c230fa6d2a6e98c5"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
    on_arm do
      sha256 "ea15258da90f1685f94329739ed3692cf83d0e90ef683ae12039c27acd8a39bd"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
  end

  name "anexia"
  desc "Command-line interface for the Anexia Engine API"
  homepage "https://github.com/ProbstenHias/anexia-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anexia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anexia"]
    end
  end

  # No zap stanza required

end
