# This file was generated by GoReleaser. DO NOT EDIT.
cask "anexia" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6774b317ce0894ca405550cd11776d38ef177043de1e3daf17ae6833cb096f87"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
    on_arm do
      sha256 "a49182565d89e08cc742772c578643c5a1df28bd7bd791758ac19c06b0f98822"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0fa547f13e2496be4618f9f2a6cc19d1e2e015a19a58a1bf528e0fa3a7dbd55"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
    on_arm do
      sha256 "169cb9c2c2071486088cae305d56707f6c038dab2877ca80e4c0efe1b0ff5c5a"
      url "https://github.com/ProbstenHias/anexia-cli/releases/download/v#{version}/anexia-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ProbstenHias/anexia-cli/"
    end
  end

  name "anexia"
  desc "Command-line interface for the Anexia Engine API"
  homepage "https://github.com/ProbstenHias/anexia-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anexia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/anexia"]
    end
  end

  # No zap stanza required

end
